# Generated by Django 5.0.4 on 2024-04-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_balance_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='user',
            new_name='user_receptor',
        ),
        migrations.AddField(
            model_name='transaction',
            name='user_emisor',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
