# Generated by Django 5.0.4 on 2024-04-15 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_rename_user_transaction_user_receptor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='state',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
