# Generated by Django 5.0.4 on 2024-04-15 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_transaction_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='state',
            new_name='type',
        ),
    ]
